### ISSUE TITLE
Serverless configuration to deploy nextjs on cloudfront

### ISSUE THREAD

**Issue by apierr** [devw/next_sls#2]
### Serverless configuration to deploy nextjs on cloudfront

```
cookiebotNextjsApp:
  component: "@sls-next/serverless-component@1.15.1"
  inputs:
    cloudfront:
      distributionId: E4LVFNYOSL9YN
    enableS3Acceleration: false
    bucketName: cookiebot-nextjs
    runtime:
      defaultLambda: "nodejs12.x"
      apiLambda: "nodejs12.x"
      imageLambda: "nodejs12.x" 
```
